
version: '3'
services:
 

  node_twiter_bot:
    image: antoine/mobileui-twitter-bot:latest
    restart: always
    expose:
    - "80"
    - "443"
    volumes:
    - ./:/usr/src/app/
    environment:
      VIRTUAL_HOST: bot.thegoodmobileui.com
      LETSENCRYPT_HOST: bot.thegoodmobileui.com
      LETSENCRYPT_EMAIL: antoinebrossault@gmail.com

  
networks:
  default:
    external:
      name: nginx-proxy

